/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiAdminContentRouteImport } from './routes/api/admin-content'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiContentRouteImport } from './routes/api/content'
import { Route as ApiCronCleanupRouteImport } from './routes/api/cron-cleanup'
import { Route as ApiMemoryMediaRouteImport } from './routes/api/memory-media'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiUploadsFilenameRouteImport } from './routes/api/uploads.$filename'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentRoute = ApiAdminContentRouteImport.update({
  id: '/api/admin-content',
  path: '/api/admin-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentRoute = ApiContentRouteImport.update({
  id: '/api/content',
  path: '/api/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCleanupRoute = ApiCronCleanupRouteImport.update({
  id: '/api/cron-cleanup',
  path: '/api/cron-cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryMediaRoute = ApiMemoryMediaRouteImport.update({
  id: '/api/memory-media',
  path: '/api/memory-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsFilenameRoute = ApiUploadsFilenameRouteImport.update({
  id: '/api/uploads/$filename',
  path: '/api/uploads/$filename',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/admin-content': typeof ApiAdminContentRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/contact': typeof ApiContactRoute
  '/api/content': typeof ApiContentRoute
  '/api/cron-cleanup': typeof ApiCronCleanupRoute
  '/api/memory-media': typeof ApiMemoryMediaRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/admin-content': typeof ApiAdminContentRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/contact': typeof ApiContactRoute
  '/api/content': typeof ApiContentRoute
  '/api/cron-cleanup': typeof ApiCronCleanupRoute
  '/api/memory-media': typeof ApiMemoryMediaRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/admin-content': typeof ApiAdminContentRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/contact': typeof ApiContactRoute
  '/api/content': typeof ApiContentRoute
  '/api/cron-cleanup': typeof ApiCronCleanupRoute
  '/api/memory-media': typeof ApiMemoryMediaRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/admin-content'
    | '/api/auth'
    | '/api/contact'
    | '/api/content'
    | '/api/cron-cleanup'
    | '/api/memory-media'
    | '/api/settings'
    | '/api/upload'
    | '/api/uploads/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/admin-content'
    | '/api/auth'
    | '/api/contact'
    | '/api/content'
    | '/api/cron-cleanup'
    | '/api/memory-media'
    | '/api/settings'
    | '/api/upload'
    | '/api/uploads/$filename'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/admin-content'
    | '/api/auth'
    | '/api/contact'
    | '/api/content'
    | '/api/cron-cleanup'
    | '/api/memory-media'
    | '/api/settings'
    | '/api/upload'
    | '/api/uploads/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiAdminContentRoute: typeof ApiAdminContentRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiContentRoute: typeof ApiContentRoute
  ApiCronCleanupRoute: typeof ApiCronCleanupRoute
  ApiMemoryMediaRoute: typeof ApiMemoryMediaRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiUploadsFilenameRoute: typeof ApiUploadsFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-content': {
      id: '/api/admin-content'
      path: '/api/admin-content'
      fullPath: '/api/admin-content'
      preLoaderRoute: typeof ApiAdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content': {
      id: '/api/content'
      path: '/api/content'
      fullPath: '/api/content'
      preLoaderRoute: typeof ApiContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron-cleanup': {
      id: '/api/cron-cleanup'
      path: '/api/cron-cleanup'
      fullPath: '/api/cron-cleanup'
      preLoaderRoute: typeof ApiCronCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory-media': {
      id: '/api/memory-media'
      path: '/api/memory-media'
      fullPath: '/api/memory-media'
      preLoaderRoute: typeof ApiMemoryMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$filename': {
      id: '/api/uploads/$filename'
      path: '/api/uploads/$filename'
      fullPath: '/api/uploads/$filename'
      preLoaderRoute: typeof ApiUploadsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiAdminContentRoute: ApiAdminContentRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiContactRoute: ApiContactRoute,
  ApiContentRoute: ApiContentRoute,
  ApiCronCleanupRoute: ApiCronCleanupRoute,
  ApiMemoryMediaRoute: ApiMemoryMediaRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiUploadsFilenameRoute: ApiUploadsFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
